"""baseline current schema

Revision ID: 20260718_0001
Revises:
Create Date: 2026-07-18 10:10:50.483194
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260718_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applied_assistant_actions",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidate_confirmations",
        sa.Column("application_id", sa.String(length=160), nullable=False),
        sa.Column("question_id", sa.String(length=160), nullable=False),
        sa.Column("requirement", sa.String(length=500), nullable=False),
        sa.Column("response", sa.String(length=16), nullable=False),
        sa.Column("example_text", sa.String(length=1500), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("application_id", "question_id"),
    )
    op.create_table(
        "candidate_match_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_input_hash", sa.String(length=64), nullable=False),
        sa.Column("profile_hash", sa.String(length=64), nullable=False),
        sa.Column("matcher_version", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("openclaw_error", sa.String(length=240), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_match_snapshots_matcher_version"),
        "candidate_match_snapshots",
        ["matcher_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_match_snapshots_profile_hash"),
        "candidate_match_snapshots",
        ["profile_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_match_snapshots_profile_input_hash"),
        "candidate_match_snapshots",
        ["profile_input_hash"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("context_kind", sa.String(length=32), nullable=False),
        sa.Column("context_id", sa.String(length=160), nullable=False),
        sa.Column("openclaw_session_key", sa.String(length=500), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_archived"), "conversations", ["archived"], unique=False)
    op.create_index(
        op.f("ix_conversations_updated_at"), "conversations", ["updated_at"], unique=False
    )
    op.create_table(
        "document_pack_jobs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("application_id", sa.String(length=160), nullable=False),
        sa.Column("persistence_mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("document_ids", sa.JSON(), nullable=False),
        sa.Column("stages", sa.JSON(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_pack_jobs_application_id"),
        "document_pack_jobs",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "document_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("file_name", sa.String(length=240), nullable=False),
        sa.Column("content_type", sa.String(length=160), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_templates_type"), "document_templates", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_document_templates_updated_at"), "document_templates", ["updated_at"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("job_id", sa.String(length=160), nullable=True),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_job_id"), "documents", ["job_id"], unique=False)
    op.create_index(op.f("ix_documents_type"), "documents", ["type"], unique=False)
    op.create_index(op.f("ix_documents_updated_at"), "documents", ["updated_at"], unique=False)
    op.create_table(
        "job_match_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=160), nullable=False),
        sa.Column("profile_hash", sa.String(length=64), nullable=False),
        sa.Column("matcher_version", sa.String(length=64), nullable=False),
        sa.Column("feedback", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_match_feedback_job_id"), "job_match_feedback", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_match_feedback_matcher_version"),
        "job_match_feedback",
        ["matcher_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_match_feedback_profile_hash"),
        "job_match_feedback",
        ["profile_hash"],
        unique=False,
    )
    op.create_table(
        "job_matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=160), nullable=False),
        sa.Column("profile_hash", sa.String(length=64), nullable=False),
        sa.Column("matcher_version", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("gaps", sa.JSON(), nullable=False),
        sa.Column("heuristic_score", sa.Integer(), nullable=False),
        sa.Column("openclaw_error", sa.String(length=240), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_matches_cache_key"), "job_matches", ["cache_key"], unique=False)
    op.create_index(op.f("ix_job_matches_job_id"), "job_matches", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_job_matches_matcher_version"), "job_matches", ["matcher_version"], unique=False
    )
    op.create_index(
        op.f("ix_job_matches_profile_hash"), "job_matches", ["profile_hash"], unique=False
    )
    op.create_table(
        "profile_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profile_versions_profile_id"), "profile_versions", ["profile_id"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stored_application_events",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("application_id", sa.String(length=160), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stored_application_events_application_id"),
        "stored_application_events",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "stored_applications",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stored_jobs",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_attachments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "application_id", name="uq_document_attachments_application"
        ),
    )
    op.create_index(
        op.f("ix_document_attachments_application_id"),
        "document_attachments",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_attachments_document_id"),
        "document_attachments",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "document_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=True),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["document_templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version", name="uq_document_files_version"),
    )
    op.create_index(
        op.f("ix_document_files_document_id"), "document_files", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_files_template_id"), "document_files", ["template_id"], unique=False
    )
    op.create_table(
        "document_generation_provenance",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("generation_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("generation_model", sa.String(length=160), nullable=False),
        sa.Column("input_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        op.f("ix_document_generation_provenance_generation_fingerprint"),
        "document_generation_provenance",
        ["generation_fingerprint"],
        unique=False,
    )
    op.create_table(
        "document_version_generation_provenance",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("generation_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("generation_model", sa.String(length=160), nullable=False),
        sa.Column("input_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "version"),
    )
    op.create_index(
        op.f("ix_document_version_generation_provenance_generation_fingerprint"),
        "document_version_generation_provenance",
        ["generation_fingerprint"],
        unique=False,
    )
    op.create_table(
        "document_version_validations",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("factual_report", sa.JSON(), nullable=False),
        sa.Column("visual_report", sa.JSON(), nullable=False),
        sa.Column("diff_items", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "version"),
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version", name="uq_document_versions_number"),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("conversation_id", sa.String(length=160), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name="uq_messages_conversation_sequence"
        ),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_table("document_version_validations")
    op.drop_index(
        op.f("ix_document_version_generation_provenance_generation_fingerprint"),
        table_name="document_version_generation_provenance",
    )
    op.drop_table("document_version_generation_provenance")
    op.drop_index(
        op.f("ix_document_generation_provenance_generation_fingerprint"),
        table_name="document_generation_provenance",
    )
    op.drop_table("document_generation_provenance")
    op.drop_index(op.f("ix_document_files_template_id"), table_name="document_files")
    op.drop_index(op.f("ix_document_files_document_id"), table_name="document_files")
    op.drop_table("document_files")
    op.drop_index(op.f("ix_document_attachments_document_id"), table_name="document_attachments")
    op.drop_index(op.f("ix_document_attachments_application_id"), table_name="document_attachments")
    op.drop_table("document_attachments")
    op.drop_table("stored_jobs")
    op.drop_table("stored_applications")
    op.drop_index(
        op.f("ix_stored_application_events_application_id"), table_name="stored_application_events"
    )
    op.drop_table("stored_application_events")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_profile_versions_profile_id"), table_name="profile_versions")
    op.drop_table("profile_versions")
    op.drop_index(op.f("ix_job_matches_profile_hash"), table_name="job_matches")
    op.drop_index(op.f("ix_job_matches_matcher_version"), table_name="job_matches")
    op.drop_index(op.f("ix_job_matches_job_id"), table_name="job_matches")
    op.drop_index(op.f("ix_job_matches_cache_key"), table_name="job_matches")
    op.drop_table("job_matches")
    op.drop_index(op.f("ix_job_match_feedback_profile_hash"), table_name="job_match_feedback")
    op.drop_index(op.f("ix_job_match_feedback_matcher_version"), table_name="job_match_feedback")
    op.drop_index(op.f("ix_job_match_feedback_job_id"), table_name="job_match_feedback")
    op.drop_table("job_match_feedback")
    op.drop_index(op.f("ix_documents_updated_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_job_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_document_templates_updated_at"), table_name="document_templates")
    op.drop_index(op.f("ix_document_templates_type"), table_name="document_templates")
    op.drop_table("document_templates")
    op.drop_index(op.f("ix_document_pack_jobs_application_id"), table_name="document_pack_jobs")
    op.drop_table("document_pack_jobs")
    op.drop_index(op.f("ix_conversations_updated_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_archived"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(
        op.f("ix_candidate_match_snapshots_profile_input_hash"),
        table_name="candidate_match_snapshots",
    )
    op.drop_index(
        op.f("ix_candidate_match_snapshots_profile_hash"), table_name="candidate_match_snapshots"
    )
    op.drop_index(
        op.f("ix_candidate_match_snapshots_matcher_version"), table_name="candidate_match_snapshots"
    )
    op.drop_table("candidate_match_snapshots")
    op.drop_table("candidate_confirmations")
    op.drop_table("applied_assistant_actions")
    # ### end Alembic commands ###
